import { RedHatText } from '@/lib/fonts';
import { CartProvider } from '@/components/cart/cart-context';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Desserts',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${RedHatText.className}`}>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
